{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  dnsNames:
  - {{ .Values.certificate.dnsName }}
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.certificate.issuerRef.name }}
  secretName: {{ .Values.certificate.secretName }}
  usages:
  - server auth
  - client auth
  - digital signature
  jks:
    create: {{ .Values.certificate.jks.create }}
    passwordSecretRef:
      name: {{ .Values.certificate.jks.passwordSecretRef.name }}
      key: {{ .Values.certificate.jks.passwordSecretRef.key }}
{{- end }}
