{{- if .Values.config.configMapName }}
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "PolyNSI.fullname" .) }}
#  namespace: {{ .Release.Namespace }}
{{- if .Values.config.filesGlob }}
binaryData:
{{- range $path, $_ :=  .Files.Glob  .Values.config.filesGlob }}
{{ $path | base | indent 2 }}: |-
{{ $.Files.Get $path | b64enc | indent 4 }}
{{- end }}
{{- else }}
{{- if or .Values.config.inline .Values.config.inlineData }}
data:
{{- end }}
{{- if .Values.config.inline }} {{/* check inline for backwards compatibility */}}
{{.Values.config.inline | indent 2}}
{{- end }}
{{- if .Values.config.inlineData }}
{{.Values.config.inlineData | indent 2}}
{{- end }}
{{- if .Values.config.inlineBinaryData }}
binaryData:
{{.Values.config.inlineBinaryData | indent 2}}
{{- end }}
{{- end }}
{{- end }}
